# Generated by Django 4.1 on 2022-09-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('action', models.IntegerField()),
                ('adventure', models.IntegerField()),
                ('romantic', models.IntegerField()),
                ('horror', models.IntegerField()),
                ('mystery', models.IntegerField()),
                ('scifi', models.IntegerField()),
                ('comedy', models.IntegerField()),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
    ]
