# Generated by Django 4.1 on 2022-09-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_webapp', '0003_rename_username_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
    ]
