# Generated by Django 4.1 on 2022-09-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_webapp', '0004_rename_email_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likedmovies',
            field=models.TextField(null=True),
        ),
    ]
